name: Multi-Arch Parallel Build (Minecraft)

on:
    push:
        branches: ["main", "master"]
        paths:
            - "@minecraft-server/**"
            - ".github/workflows/build-minecraft-server.yml"
    workflow_dispatch:

env:
    PACKAGE_SHORT_NAME: minecraft-server
    REGISTRY: ${{ vars.DOCKER_REGISTRY || 'ghcr.io'}}
    REGISTRY_TOKEN: ${{ secrets.PACKAGES_TOKEN || secrets.GITHUB_TOKEN }}
    BUILDKITD_CONFIG_FILE: .github/${{ vars.BUILDKITD_CONFIG_FILE || 'buildkitd.toml' }}
    # 注意：如果 github.repository_owner 包含大写字母，这里会直接导致后续 Docker 报错。
    # 只要全小写用户（组织）名，这就没问题。
    FULL_IMAGE_NAME: ${{ vars.DOCKER_REGISTRY || 'ghcr.io'}}/${{ github.repository_owner }}/minecraft-server

jobs:
    # Job 1: 构建 amd64
    build-amd64:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  buildkitd-config: ${{ env.BUILDKITD_CONFIG_FILE }}

            - name: Login to Docker Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ env.REGISTRY_TOKEN }}

            - name: Build and push (amd64)
              uses: docker/build-push-action@v5
              with:
                  context: ./@minecraft-server
                  platforms: linux/amd64
                  push: true
                  tags: ${{ env.FULL_IMAGE_NAME }}:latest-amd64
                  provenance: false
                  cache-from: type=registry,ref=${{ env.FULL_IMAGE_NAME }}:buildcache-amd64
                  cache-to: type=registry,ref=${{ env.FULL_IMAGE_NAME }}:buildcache-amd64,mode=max

    # Job 2: 构建 arm64
    build-arm64:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  buildkitd-config: ${{ env.BUILDKITD_CONFIG_FILE }}

            - name: Login to Docker Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ env.REGISTRY_TOKEN }}

            - name: Build and push (arm64)
              uses: docker/build-push-action@v5
              with:
                  context: ./@minecraft-server
                  platforms: linux/arm64
                  push: true
                  tags: ${{ env.FULL_IMAGE_NAME }}:latest-arm64
                  provenance: false
                  cache-from: type=registry,ref=${{ env.FULL_IMAGE_NAME }}:buildcache-arm64
                  cache-to: type=registry,ref=${{ env.FULL_IMAGE_NAME }}:buildcache-arm64,mode=max

    # Job 3: 合并与清理
    merge-manifest:
        runs-on: ubuntu-latest
        needs: [build-amd64, build-arm64]
        permissions:
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  buildkitd-config: ${{ env.BUILDKITD_CONFIG_FILE }}

            - name: Login to Docker Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ env.REGISTRY_TOKEN }}

            - name: Create and push manifest list
              run: |
                  TARGET_IMAGE="${{ env.FULL_IMAGE_NAME }}:latest"
                  AMD64_IMAGE="${{ env.FULL_IMAGE_NAME }}:latest-amd64"
                  ARM64_IMAGE="${{ env.FULL_IMAGE_NAME }}:latest-arm64"

                  docker buildx imagetools create -t ${TARGET_IMAGE} \
                    ${AMD64_IMAGE} \
                    ${ARM64_IMAGE}
