name: Guard for GitHub

on:
    workflow_call:

jobs:
    check-env:
        if: github.server_url == 'https://github.com'
        runs-on: ubuntu-latest
        steps:
            - name: Environment Check
              run: echo Action runs on GitHub
